name: Terraform Validate & Apply

on:
  workflow_dispatch:  
  pull_request:
    # dispatch when pull request on main, from aws_backend or src folder
    branches:
      - main
    paths:
      - "aws_backend/**"
      - "src/**"
  push:
    branches:
      - main
    paths:
      - "aws_backend/**"
      - "src/**"

jobs:
  opentofu:
    name: Terraform Validate & Apply
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }} 
      AWS_DEFAULT_REGION: "us-east-1"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup OpenTofu (Terraform)
        uses: opentofu/setup-opentofu@v1
        with:
          tofu_version: 1.6.0

      - name: Initialize OpenTofu
        working-directory: aws_backend
        run: tofu init

      - name: Validate OpenTofu Configuration 
        working-directory: aws_backend
        run: tofu validate

      - name: Generate Execution Plan
        working-directory: aws_backend
        run: tofu plan -out=tfplan

      - name: Apply OpenTofu Changes (Only on main)
        if: github.ref == 'refs/heads/main'
        working-directory: aws_backend
        run: tofu apply -auto-approve tfplan